### ISSUE TITLE
Where is the firestore exported data located by default on windows?

### ISSUE THREAD

**Issue by elieobeid7** [benyap/firestore-backfire#161]
I installed the package globally on Windows 11

 `npm install -g firestore-backfire @google-cloud/firestore`

And I didn't notice that I have to use the full path, so I used a relative path instead

`backfire export . -p database -k credentials.json`

and 

`backfire export data -p database -k credentials.json`

Where are the data located by default in order to delete it?

**Comment by benyap** [comment]
Hey @elieobeid7, I don't personally use Windows so I can't say I know for sure. But you can try adding the **logLevel** flag when you run `backfire` which will output some useful information that might help you track down where your data is.

For example:
```
backfire export . -p database -k credentials.json --logLevel debug
```

**Comment by benyap** [comment]
Hey @elieobeid7, haven't heard back from you, so I'm going to close this issue for now. Feel free to re-open if you have any further questions.
