### ISSUE TITLE
>  TypeError: _this.writer.open is not a function

### ISSUE THREAD

**Issue by minuitagency** [benyap/firestore-backfire#240]
Hi, 

Thanks for the great library, 

I have the error in the title while tying to implemlent, here's our code:

`   const result = await exportFirestoreData(
              {
                project: firebaseProjectID,
                credentials,
              },
              {
                path: `gs://...`,
                gcpProject: "...",
                gcpCredentials: {
                  type: "service_account",
                  ...
                },
              }
            );`

Thanks, 

Théo

**Comment by benyap** [comment]
Hi @minuitagency,

Thanks for using this library!

Please refer to the documentation for how to use the [exportFirestoreData](https://github.com/benyap/firestore-backfire#exporting-data) function.

From the code you've provided, it looks like you haven't supplied the correct arguments to the function. The second argument should be an instance of an object that satisfies the [IDataSourceWriter](https://github.com/benyap/firestore-backfire/blob/main/src/data-source/interface/writer.ts) interface, and the options object you have should be the third argument. See below:

```js
// Please ensure you provide the `writer` parameter
await exportFirestoreData(connection, writer, options);
```

Are you trying to export data to a local file, or to S3/Google Cloud Storage? These are the default IDataSourceWriter implementations [provided by this library](https://github.com/benyap/firestore-backfire#data-sources), which you can use by following the documentation [here](https://github.com/benyap/firestore-backfire#creating-a-data-source-in-node).

Hope this is helps - please let me know if you need further assistance 😊

**Comment by BieniekAlexander** [comment]
@benyap I can't get writing to local work:
```js
let firestore = new Firestore({ projectId: PROJECT_ID, keyFilename: process.env.PATH_TO_FIRESTORE_CREDS })
let writer = dataSourceFactory.createWriter("./out.ndjson")
let paths = ['collection']

exportFirestoreData({
    connection: firestore,
    writer: writer,
    options: {
        paths: paths
    }
})
```

```bash
/home/alex/work/mlops-product-landscape/node_modules/firestore-backfire/dist/cjs/actions/exportFirestoreData/exportFirestoreData.js:157
                    path = (0, _utils.dir)(writer.path);
                                                  ^

TypeError: Cannot read properties of undefined (reading 'path')
```

**Comment by benyap** [comment]
Hi @minuitagency, haven't heard back so I'm going to close this for now.

Feel free to re-open if you are encountering further issues.
