### ISSUE TITLE
Using project name and ApiKey

### ISSUE THREAD

**Issue by kheireddine-saidi** [benyap/firestore-backfire#241]
Is it possible to use only project name and ApiKey to access the data?

**Comment by benyap** [comment]
Hi @kheireddine-saidi,

I assume you're referring to the Project ID and API Key in your [Firebase client config](https://firebase.google.com/docs/web/learn-more#config-object) - the answer is no. Those credentials are for use on the client side only.

Firestore Backfire uses the [Admin SDK](https://firebase.google.com/docs/admin/setup) to read and write data to Firestore, and is only intended to be in secure environments (i.e. on the backend) where you can provide secrets such as the private key securely.
