### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position 20441 

### ISSUE THREAD

**Issue by nonoumasy** [benyap/firestore-backfire#347]
I exported my Firestore collection (88mb). Since I'm not familiar with the data structure of this export, I used JSON.parse() to find it.

```
import * as fs from "fs"
const filePath = JSON.parse(fs.readFileSync("../../data/hm.ndjson"))

const readStream = fs.createReadStream(filePath, { encoding: "utf8" })

readStream.on("data", (chunk) => {
  const lines = chunk.split("\n")
  lines.forEach((line) => {
    if (line.trim() !== "") {
      try {
        const jsonObject = JSON.parse(line)
        // Analyze the structure of `jsonObject` here
        console.log(jsonObject)
      } catch (error) {
        console.error("Error parsing line:", line)
      }
    }
  })
})

readStream.on("end", () => {
  console.log("Finished reading the NDJSON file.")
})

readStream.on("error", (error) => {
  console.error("Error reading the file:", error)
})
```

1.
It gave this error:
SyntaxError: Unexpected non-whitespace character after JSON at position 20441
    at JSON.parse (<anonymous>)
    at file:///Users/nonoumasy/Downloads/node/transform/findJSONStructure.js:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    
I looked into the issue, and it seems to have issue with the _nanoseconds property. I'm not sure why 🤷‍♂️.
  

2.
Also VScode was unable to prettify the NDJSON file because the filesizes was too big, any suggestions on how to view it?

**Comment by nonoumasy** [comment]
Ok. I researched more into ndjson and its a little different from JSON structure. It seems that when the Firestore data is exported (since technically there are no subcollections in Firebase), the ndjson file is basically a list/array of all the documents. So the so-called 'subcollections' are not nested. Good to know. I was able to get the work with it using:

```
import * as fs from "fs"

const ndjsonFilePath = "../../data/hm.ndjson"

fs.readFile(ndjsonFilePath, "utf8", (err, data) => {
  if (err) {
    console.error("Error reading NDJSON file:", err)
    return
  }

  // Process the NDJSON data
  processData(data)
})

function processData(data) {
  const jsonLines = data.split("\n")
  console.log(jsonLines.length)
  for (const line of jsonLines) {
    // Skip empty lines
    if (line.trim() === "") {
      continue
    }

    // Parse the JSON object
    try {
      const jsonObject = JSON.parse(line)
      // Process the JSON object as needed
      console.log(jsonObject.data.title)
    } catch (error) {
      console.error("Error parsing JSON object:", error)
    }
  }
}

```

**Comment by benyap** [comment]
Hey @nonoumasy glad you figured it out. The shape of the NDJSON objects follow [this interface](https://github.com/benyap/firestore-backfire/blob/main/src/firestore/FirestoreDocument/types.ts#L15-L28). Thought I'd mention it in case it's helpful 🙂

**Comment by nonoumasy** [comment]
I tried importing the data back. It was taking more than an hour. It didn't take that long to export so there must be an issue. As a precaution, I imported it to a test firestore project.
